    - name: download the application
      get_url: url=https://s3.amazonaws.com/amcaar/mpi_gene.tar.gz dest=/home/user1/mpi_gene.tar.gz
    
    - name: decompress the application
      command: tar xvf mpi_gene.tar.gz chdir=/home/user1/

    - name: give execution permissions to the launcher script
      command: chmod u+x launch.sh chdir=/home/user1/mpi_gene

    - name: generate parameters file
      command: ./generate_parameters.sh 16 0.1 100 chdir=/home/user1/mpi_gene

    - name: change the owner of the application
      command: chown -R user1:user1 /home/user1/mpi_gene
