    - name: update repositories cache and install slurm dependences
      apt: pkg=nfs-common update_cache=yes cache_valid_time=3600

    - name: mount the shared directories
      command: mount -t nfs {{ groups['front'][0]['IM IM_NODE_NET_1_IP']}}:/home /home creates=/home/ubuntu/pyslurm

